---
# tasks file for ssmtp

- name: Include distribution specific variables
  include_vars: "{{ ansible_os_family }}.yml"
  tags: ssmtp

- include: RedHat.yml
  when: ansible_os_family == "RedHat"
  tags: ssmtp

- include: Debian.yml
  when: ansible_os_family == "Debian"
  tags: ssmtp

- name: Create sSMTP revaliases file
  template: >
    src=revaliases.j2
    dest=/etc/ssmtp/revaliases
    owner=root
    group=root
    mode=0644
  tags: ssmtp

- name: Create sSMTP configuration file
  template: >
    src=ssmtp.conf.j2
    dest=/etc/ssmtp/ssmtp.conf
    owner=root
    group=root
    mode=0640
  tags: ssmtp
